### PR TITLE
Finally created a better logo

### PR DESCRIPTION
**Pull request by Nick-Toons**
It looks better than just an android guy in a circle in a box

### CODE REVIEW

**Comment by amikhalev** [comment]
Nice! Did you make it yourself?

**Comment by Nick-Toons** [comment]
I found a stock image and edited it, yes.

**Comment by amikhalev** [comment]
Creative Commons licensed? Are we going to get sued?

(you can probably merge this)

**Comment by Nick-Toons** [comment]
No, we aren't going to get sued, I'll merge it tomorrow.

**Pull request merged**
